export const AllProjects = [
    {
        id:1,
        name:"Conference APP",
        description:"",
        category:"Works",
        link:"https://efxrd.com",
        stack:"",
        pictures:{
            principal:'',
            extraPrictures:[
                '',
                '',
                ''
            ]
        }
    },
    {
        id:2,
        name:"LS Tracking",
        description:"",
        category:"Works",
        link:"https://lstracking.com",
        stack:"",
        pictures:{
            principal:'',
            extraPrictures:[
                '',
                '',
                ''
            ]
        }
    },
    {
        id:3,
        name:"Pleelo",
        description:"",
        category:"Works",
        link:"https://pleelo.com",
        stack:"",
        pictures:{
            principal:'',
            extraPrictures:[
                '',
                '',
                ''
            ]
        }
    },
    {
        id:3,
        name:"Basket",
        description:"",
        category:"Collaborations",
        link:"https://basket.do",
        stack:"",
        pictures:{
            principal:'',
            extraPrictures:[
                '',
                '',
                ''
            ]
        }
    }
]