//import pleelo from "../assets/projects/pleelo/pleelo_principal.png"

export const AllProjects = [
    {
        id:1,
        name:"Conference APP",
        description:"",
        category:"Works",
        link:"https://efxrd.com",
        stack:"",
        pictures:{
            principal:'src/assets/projects/conferenceapp/conferenceapp_principal.png',
            extraPrictures:[
                '',
                '',
                ''
            ]
        }
    },
    {
        id:2,
        name:"LS Tracking",
        description:"",
        category:"Works",
        link:"https://lstracking.com",
        stack:"",
        pictures:{
            principal:'src/assets/projects/lstracking/lstracking_principal.png',
            extraPrictures:[
                '',
                '',
                ''
            ]
        }
    },
    {
        id:3,
        name:"Pleelo",
        description:"",
        category:"Works",
        link:"https://pleelo.com",
        stack:"",
        pictures:{
            principal:'src/assets/projects/pleelo/pleelo_principal.png',
            extraPrictures:[
                '',
                '',
                ''
            ]
        }
    },
    {
        id:3,
        name:"Basket",
        description:"",
        category:"Collaborations",
        link:"https://basket.do",
        stack:"",
        pictures:{
            principal:'src/assets/projects/basket/basket_principal.png',
            extraPrictures:[
                '',
                '',
                ''
            ]
        }
    },{
        id:4,
        name:"Auction Online",
        description:"",
        category:"Own Projects",
        link:"#",
        stack:"",
        pictures:{
            principal:'src/assets/projects/auction_online/auctiononline_principal.jpg',
            extraPrictures:[
                '',
                '',
                ''
            ]
        }
    },
    {
        id:5,
        name:"Sarez Elevadores",
        description:"",
        category:"Own Projects",
        link:"#",
        stack:"",
        pictures:{
            principal:'src/assets/projects/sarez_elevadores/sarezelevadores_principal.jpg',
            extraPrictures:[
                '',
                '',
                ''
            ]
        }
    }
]